import { Providers } from "@/Features/provider";
import ProvidersWrapper from "./ProvidersWrapper";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Eshkon App",
  description: "Generated by Divya Vadranam",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ProvidersWrapper> {children}</ProvidersWrapper>
        </Providers>
      </body>
    </html>
  );
}
